name: Update .storage-layout

on:
  workflow_dispatch:

jobs:
  assert:
    runs-on: ubuntu-latest
    name: Update storage layout
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node.js version
        uses: actions/setup-node@v4
        with:
          node-version: 16.x
          cache: 'yarn'

      - name: Install yarn deps
        run: yarn

      - name: Generate new .storage-layout
        uses: lidofinance/storage-layout-action@v1
        with:
          mode: generate
          src-folder: ./contracts
          ignore-folders: '{test_helpers,template,mocks}'

      - name: Create Pull Request
        uses: lidofinance/create-pull-request@v4
        with:
          add-paths: .storage-layout
          branch: update-storage-layout-${{ github.ref_name }}
          delete-branch: true
          commit-message: 'fix: Make storage-layout up to date'
          title: 'Update .storage-layout for ${{ github.ref_name }} branch'
          body: 'This PR is generated automatically. Merge it to apply new version of .storage-layout'
