name: Assert storage layout changes

on:
  push:
    branches: [develop, master]
  pull_request:
    branches: [develop, master]

jobs:
  assert:
    runs-on: ubuntu-latest
    name: Assert storage layout
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node.js version
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: 'yarn'

      - name: Submodules
        run: git submodule update --init --recursive

      - name: Install yarn deps
        run: yarn

      - name: Check storage-layout
        uses: lidofinance/storage-layout-action@v1
        with:
          mode: check
          src-folder: ./contracts
          ignore-folders: '{test_helpers,template,mocks}'
