name: Unit Tests

on: [push]

jobs:
  test_hardhat_unit:
    name: Hardhat
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Common setup
        uses: ./.github/workflows/setup

      - name: Run unit tests
        run: yarn test

  test_foundry_fuzzing:
    name: Foundry (fuzzing & invariant)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Common setup
        uses: ./.github/workflows/setup

      - name: Install foundry
        uses: foundry-rs/foundry-toolchain@v1
        # Use a specific version of Foundry in case nightly is broken
        # https://github.com/foundry-rs/foundry/releases
        # with:
        #   version: nightly-54d8510c0f2b0f791f4c5ef99866c6af99b7606a

      - name: Run fuzzing and invariant tests
        run: forge test -vvv
